name: Build contracts
run-name: build

on:
  workflow_call:
    outputs:
      image_tag:
        description: "Image tag pushed to non-prod ECR"
        value: ${{ jobs.build.outputs.image_tag }}
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

env:
  ECR_REPO: ab2d-contracts
  TAG_PREFIX: contracts-service
  AWS_ACCOUNT: ${{ secrets.GF_NON_PROD_ACCOUNT }}
  RUNNER: codebuild-ab2d-contracts-${{github.run_id}}-${{github.run_attempt}}

jobs:
  build:
    runs-on: ${{ env.RUNNER }}
    outputs:
      image_tag: ${{ steps.build_image.outputs.image_tag }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '17'

      - uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: 8.4

      - uses: cmsgov/cdap/actions/aws-params-env-action@main
        with:
          params: |
            ARTIFACTORY_URL=/artifactory/url
            ARTIFACTORY_USER=/artifactory/user
            ARTIFACTORY_PASSWORD=/artifactory/password

      - name: Assume role in target account
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ vars.AWS_REGION }}
          role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT }}:role/delegatedadmin/developer/ab2d-dev-github-actions

      - name: Build libraries
        run: |
          gradle -b build.gradle bootJar -Dset.root.project.build.filename=true

      - name: Build and push docker image
        id: build_image
        run: |
          ECR_DOMAIN="$AWS_ACCOUNT.dkr.ecr.$AWS_REGION.amazonaws.com"
          SHA_SHORT=$(git rev-parse --short HEAD)
          ECR_URI="$ECR_DOMAIN/$ECR_REPO"
          BRANCH_NAME_FORMATTED=${GITHUB_REF_NAME//\//-}
          TAG_SHORT="$TAG_PREFIX-$BRANCH_NAME_FORMATTED-$SHA_SHORT"
          aws ecr get-login-password | docker login --username AWS --password-stdin $ECR_DOMAIN
          docker build -t "$ECR_URI:$TAG_SHORT" .
          docker push "$ECR_URI" --all-tags
          echo "Published **$ECR_URI:$TAG_SHORT**" >> $GITHUB_STEP_SUMMARY
          echo "image_tag=$TAG_SHORT" >> $GITHUB_OUTPUT
