name: Build & deploy contracts
run-name: Build & deploy

permissions:
  contents: read
  id-token: write

on:
  push:
    branches:
      - AB2D-6840/fix_ci
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
  workflow_dispatch:
    inputs:
      environment:
        description: AB2D environment
        required: true
        type: choice
        options:
          - dev
          - test

jobs:
  build:
    uses: ./.github/workflows/build-minimal.yml
    secrets: inherit
  deploy:
    needs: [build]
    uses: ./.github/workflows/deploy.yml
    with:
      IMAGE_TAG: ${{ needs.build.outputs.image_tag }}
    secrets: inherit
