name: Build & deploy contracts
run-name: build-deploy ${{ inputs.environment }}

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      run_tests:
        type: boolean
        default: true
  workflow_dispatch:
    inputs:
      environment:
        description: AB2D environment
        required: true
        type: choice
        options:
          - dev
          - test
      run_tests:
        description: Run tests
        type: boolean
        default: true

permissions:
  contents: read
  id-token: write

concurrency:
  group: build-deploy-${{ inputs.environment }}

jobs:
  build:
    uses: ./.github/workflows/build.yml
    secrets: inherit
    with:
      run_tests: ${{ inputs.run_tests }}
      push_image: true

  deploy:
    needs: [build]
    uses: ./.github/workflows/deploy.yml
    with:
      environment: ${{ inputs.environment }}
      image_tag: ${{ needs.build.outputs.image_tag }}
    secrets: inherit

  sonarqube:
    if: ${{ inputs.run_sonar == true }}
    uses: ./.github/workflows/sonarqube.yml
    secrets: inherit
