name: Deploy contracts GF
run-name: deploy-gf ${{ inputs.environment }} ${{ inputs.image_tag_suffix }}

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      tag_suffix:
        required: true
        type: string
  workflow_dispatch:
    inputs:
      environment:
        description: AB2D environment
        required: true
        type: choice
        options:
          - dev
          - test
          - sandbox
          - prod
      image_tag_suffix:
        description: Image tag suffix
        required: false
        type: string

jobs:
  apply_tofu:
    permissions:
      contents: read
      id-token: write
    uses: cmsgov/ab2d/.github/workflows/terraform-microservices-gf.yml@more-workflows-gf # TODO set to main
    with:
      environment: ${{ inputs.environment }}
      contracts_service_image: contracts-service-${{ inputs.image_tag_suffix || github.ref }}
      apply: true
      ref: main
      runner: codebuild-ab2d-contracts-${{github.run_id}}-${{github.run_attempt}}
    secrets:
      aws_account: ${{contains(fromJSON('["dev", "test"]'), inputs.environment) && secrets.GF_NON_PROD_ACCOUNT || secrets.GF_PROD_ACCOUNT}}
