name: promote-contracts

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
  workflow_dispatch:
    inputs:
      environment:
        required: true
        type: choice
        options:
          - prod_test
          - prod

permissions:
  contents: read
  id-token: write

jobs:
  promote:
    runs-on: self-hosted
    steps:
      - name: Set environment
        id: set-env
        run: |
          echo "env_name=${{ inputs.environment }}" >> $GITHUB_OUTPUT

      - name: Define source/destination config
        id: repos
        run: |
          if [ "${{ steps.set-env.outputs.env_name }}" == "prod_test" ]; then
            echo "SOURCE_ENV=test" >> $GITHUB_OUTPUT
            echo "SOURCE_REPO=ab2d-impl-services" >> $GITHUB_OUTPUT
            echo "DEST_REPO=ab2d-prod-test-services" >> $GITHUB_OUTPUT
          elif [ "${{ steps.set-env.outputs.env_name }}" == "prod" ]; then
            echo "SOURCE_ENV=prod_test" >> $GITHUB_OUTPUT
            echo "SOURCE_REPO=ab2d-prod-test-services" >> $GITHUB_OUTPUT
            echo "DEST_REPO=ab2d-prod-services" >> $GITHUB_OUTPUT
          fi
          echo "TAG_NAME=contracts-service" >> $GITHUB_ENV

      - name: Authenticate to source account (pull)
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          aws-region: ${{ vars.AWS_REGION }}
          role-to-assume: arn:aws:iam::${{ secrets[format('{0}_ACCOUNT', steps.repos.outputs.SOURCE_ENV)] }}:role/delegatedadmin/developer/ab2d-${{ steps.repos.outputs.SOURCE_ENV }}-github-actions

      - name: Pull image from source ECR
        id: pull-image
        env:
          AWS_REGION: ${{ vars.AWS_REGION }}
          SOURCE_REPO: ${{ steps.repos.outputs.SOURCE_REPO }}
          TAG_NAME: contr
