name: promote-contracts

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
  workflow_dispatch:
    inputs:
      environment:
        required: true
        type: choice
        options:
          - prod_test
          - prod
  pull_request:
    branches:
      - main

permissions:
  contents: read
  id-token: write

jobs:
  promote:
    runs-on: self-hosted
    steps:
      - name: Determine promotion environment
        id: set-env
        run: |
          if [ "${{ github.event_name }}" == "pull_request" ]; then
            echo "env_name=prod_test" >> $GITHUB_OUTPUT
          else
            echo "env_name=${{ inputs.environment }}" >> $GITHUB_OUTPUT
          fi
      - name: Define source/destination config
        id: repos
        run: |
          if [ "${{ steps.set-env.outputs.env_name }}" == "prod_test" ]; then
            echo "SOURCE_ENV=test" >> $GITHUB_OUTPUT
            echo "SOURCE_REPO=ab2d-impl-services" >> $GITHUB_OUTPUT
            echo "DEST_REPO=ab2d-prod-test-services" >> $GITHUB_OUTPUT
          elif [ "${{ steps.set-env.outputs.env_name }}" == "prod" ]; then
            echo "SOURCE_ENV=prod_test" >> $GITHUB_OUTPUT
            echo "SOURCE_REPO=ab2d-prod-test-services" >> $GITHUB_OUTPUT
            echo "DEST_REPO=ab2d-prod-services" >> $GITHUB_OUTPUT
          fi
          echo "TAG_NAME=contracts-service" >> $GITHUB_ENV
      - name: Authenticate to source account (pull)
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          aws-region: ${{ vars.AWS_REGION }}
          role-to-assume: arn:aws:iam::${{ secrets[format('{0}_ACCOUNT', steps.repos.outputs.SOURCE_ENV)] }}:role/delegatedadmin/developer/ab2d-${{ steps.repos.outputs.SOURCE_ENV }}-github-actions

      - name: Pull image from source ECR
        id: pull-image
        env:
          AWS_REGION: ${{ vars.AWS_REGION }}
          SOURCE_REPO: ${{ steps.repos.outputs.SOURCE_REPO }}
          TAG_NAME: contracts-service
        run: |
          ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
          SRC_ECR="$ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com"
          docker login --username AWS --password-stdin $SRC_ECR <<< $(aws ecr get-login-password)
          echo "Pulling $SRC_ECR/$SOURCE_REPO:$TAG_NAME"
          docker pull "$SRC_ECR/$SOURCE_REPO:$TAG_NAME"
          echo "SRC_ECR=$SRC_ECR" >> $GITHUB_OUTPUT
          echo "IMAGE=$SRC_ECR/$SOURCE_REPO:$TAG_NAME" >> $GITHUB_OUTPUT
      - name: Authenticate to destination account (push)
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          aws-region: ${{ vars.AWS_REGION }}
          role-to-assume: arn:aws:iam::${{ secrets.prod_ACCOUNT }}:role/delegatedadmin/developer/ab2d-prod-github-actions

      - name: Tag and push image to destination ECR
        env:
          AWS_REGION: ${{ vars.AWS_REGION }}
          DEST_REPO: ${{ steps.repos.outputs.DEST_REPO }}
          TAG_NAME: contracts-service
          IMAGE: ${{ steps.pull-image.outputs.IMAGE }}
        run: |
          ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
          DEST_ECR="$ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com"
          docker login --username AWS --password-stdin $DEST_ECR <<< $(aws ecr get-login-password)
          echo "Tagging and pushing image to $DEST_ECR/$DEST_REPO:$TAG_NAME"
          docker tag "$IMAGE" "$DEST_ECR/$DEST_REPO:$TAG_NAME"
          docker push "$DEST_ECR/$DEST_REPO:$TAG_NAME"
