name: pull request jobs

on:
  push:
    branches-ignore:
      - 'main'
  workflow_dispatch:

jobs:
  test:
    uses: ./.github/workflows/test.yml
    secrets: inherit
  build:
    needs: test
    uses: ./.github/workflows/build.yml
    with:
      environment: test
    secrets: inherit
