name: Pull request

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read
  id-token: write

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      run_tests: true
      push_image: false
    secrets: inherit
  sonarqube:
    uses: ./.github/workflows/sonarqube.yml

