name: Push to main

on:
  push:
    branches:
#      - main
      - AB2D-6840/fix_ci

permissions:
  contents: read
  id-token: write

jobs:
  build-deploy-dev:
    uses: ./.github/workflows/build-deploy.yml
    with:
      environment: dev
    secrets: inherit

  build-deploy-test:
    uses: ./.github/workflows/build-deploy.yml
    with:
      environment: test
    secrets: inherit

