
name: Test Contractors

on:
  push:
    branches-ignore:
      - 'main'
  workflow_call:
  workflow_dispatch: # Allow manual trigger

jobs:
  test:
    runs-on: self-hosted
    env:
      ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true
      AWS_REGION: ${{ vars.AWS_REGION }}
      DEPLOYMENT_ENV: ${{ vars[format('{0}_DEPLOYMENT_ENV', inputs.environment)] }}
    
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Set env vars from AWS params
        uses: cmsgov/ab2d-bcda-dpc-platform/actions/aws-params-env-action@main
        env:
          AWS_REGION: ${{ vars.AWS_REGION }}
        with:
          params: |
            ARTIFACTORY_URL=/artifactory/url
            ARTIFACTORY_USER=/artifactory/user
            ARTIFACTORY_PASSWORD=/artifactory/password
            SONAR_HOST_URL=/sonarqube/url
            SONAR_TOKEN=/sonarqube/token
            
      - name: Export ARTIFACTORY variables
        run: |
          echo "ARTIFACTORY_URL=${ARTIFACTORY_URL}" >> $GITHUB_ENV
          echo "ARTIFACTORY_USER=${ARTIFACTORY_USER}" >> $GITHUB_ENV
          echo "ARTIFACTORY_PASSWORD=${ARTIFACTORY_PASSWORD}" >> $GITHUB_ENV
          echo "HPMS_AUTH_KEY_ID=${HPMS_AUTH_KEY_ID}" >> $GITHUB_ENV
          echo "HPMS_AUTH_KEY_SECRET=${HPMS_AUTH_KEY_SECRET}" >> $GITHUB_ENV

      - name: Set up Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: '7.5'


      - name: Build files
        run: |
          gradle build -x test --info 

      - name: Do tests
        run: |
          gradle clean test --info build 

      - name: Build Jar
        run: |
          gradle jar --info build 
        
      - name: SonarQube Quality Gate check
        id: sonarqube-quality-gate-check
        uses: sonarsource/sonarqube-quality-gate-action@master
        with:
          scanMetadataReportFile: build/sonar/report-task.txt
        timeout-minutes: 5
