
name: Test Contracts

on:
  workflow_dispatch:
  workflow_call:

jobs:
  test:
    runs-on: self-hosted
    env:
      ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true
      AWS_REGION: ${{ vars.AWS_REGION }}
      DEPLOYMENT_ENV: ${{ vars[format('{0}_DEPLOYMENT_ENV', inputs.environment)] }}
    
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Set env vars from AWS params
        uses: cmsgov/ab2d-bcda-dpc-platform/actions/aws-params-env-action@main
        env:
          AWS_REGION: ${{ vars.AWS_REGION }}
        with:
          params: |
            ARTIFACTORY_URL=/artifactory/url
            ARTIFACTORY_USER=/artifactory/user
            ARTIFACTORY_PASSWORD=/artifactory/password
            SONAR_HOST_URL=/sonarqube/url
            SONAR_TOKEN=/sonarqube/token
            HPMS_AUTH_KEY_ID=/hpms/id
            HPMS_AUTH_KEY_SECRET=/hpms/secret
            

      - name: Set up Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: '7.5'


      - name: Build files
        run: |
          gradle build -x test --info 

      - name: Do tests
        run: |
          gradle clean test --info build 

      - name: Build Jar
        run: |
          gradle jar --info build 

      - name: Gradle task
        run: |
          gradle task
        
      - name: SonarQube Analysis
        run: |
          gradle sonar
          
